apiVersion: apps/v1 
kind: Deployment
metadata:
  name: lab-app
spec:
  selector:
    matchLabels:
      app: lab-app 
  replicas: 2 
  template:
    metadata:
      labels:
        app: lab-app
    spec:
#      securityContext:
#        sysctls:
#        - name: net.ipv4.tcp_congestion_control
#          value: "bbr"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - lab-app
            topologyKey: failure-domain.beta.kubernetes.io/zone 
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - lab-app
            topologyKey: kubernetes.io/hostname 
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
