apiVersion: v1
kind: Service
metadata:
  name: lab-svc
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-074e42c65fc695e3a 
spec:
  selector:
    app: lab-app
  ports:
   - port: 80
     protocol: TCP
     targetPort: http
  type: LoadBalancer
